In [1]:
# importing pandas
import pandas as pd

# csv file location
url = 'https://raw.githubusercontent.com/tariqzahratahdi/DataScience/refs/heads/main/datasets/fortune500.csv'

# making data frame from csv file
data = pd.read_csv(url, index_col = 'company')

# Indexing and Selecting Data

Indexing in Pandas means simply selecting particular rows and columns of data from a DataFrame.

Indexing could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns.

Indexing can also be known as subset selection.

Some common methods and attributes for viewing and selecting data in a Pandas DataFrame include:

* `head(n=5)` : Displays the first n rows of a DataFrame.
* `tail(n=5)` : Displays the last n rows of a DataFrame.
* `loc` : Accesses a group of rows and columns by labels or a boolean array.
* `iloc` : Accesses a group of rows and columns by integer indices.
* `columns` : Lists the column labels of the DataFrame.
* `['A']` : Selects the column named `A` from the DataFrame.

**Example**

In [2]:
# selecting data
data_selection = data.head()

data_selection

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country
company,,,,,,,,,,,
Walmart,1,485873,0.8,13643.0,198825,-7.2,C. Douglas McMillon,General Merchandisers,Retailing,1,USA
State Grid,2,315199,-4.4,9571.3,489838,-6.2,Kou Wei,Utilities,Energy,2,China
Sinopec Group,3,267518,-9.1,1257.9,310726,-65.0,Wang Yupu,Petroleum Refining,Energy,4,China
China National Petroleum,4,262573,-12.3,1867.5,585619,-73.7,Zhang Jianhua,Petroleum Refining,Energy,3,China
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan

In [3]:
# selecting data
data_selection = data.tail()

data_selection

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country
company,,,,,,,,,,,
Teva Pharmaceutical Industries,496,21903,11.5,329.0,92890,-79.3,Yitzhak Peterburg,Pharmaceuticals,Health Care,0,Israel
New China Life Insurance,497,21796,-13.3,743.9,100609,-45.6,Wan Feng,Insurance: Life Health (stock),Financials,427,China
Wm. Morrison Supermarkets,498,21741,-11.3,406.4,11630,20.4,David T. Potts,Food and Drug Stores,Food & Drug Stores,437,Britain
TUI,499,21655,-5.5,1151.7,16247,195.5,Friedrich Joussen,Travel Services,Business Services,467,Germany
AutoNation,500,21609,3.6,430.5,10060,-2.7,Michael J. Jackson,Specialty Retailers,Retailing,0,USA

# Indexing a DataFrame using indexing operator `[ ]`

Indexing operator refers to the square brackets `[ ]` following an object.

In order to select a single column, we simply put the name of the column in-between the brackets

Note: use a column name other than the index column.

**Example**

In [4]:
# selecting columns by indexing operator
data_selection = data['rank']

data_selection

company
Walmart                             1
State Grid                          2
Sinopec Group                       3
China National Petroleum            4
Toyota Motor                        5
                                 ...
Teva Pharmaceutical Industries    496
New China Life Insurance          497
Wm. Morrison Supermarkets         498
TUI                               499
AutoNation                        500
Name: rank, Length: 500, dtype: int64

Note that the instruction (`data['rank']`) will return a `Series` and not a `DataFrame`.

In [5]:
print(type(data_selection))

<class 'pandas.core.series.Series'>

To convert it to a `DataFrame`, we can enclose the single column inside the `[]` operator. The syntax will be as follows:

In [6]:
data_selection = data[['rank']]

print(type(data_selection))

<class 'pandas.core.frame.DataFrame'>

## Select multiple columns

In [16]:
# selecting columns by indexing operator
data_selection = data[['rank', 'revenues']]

data_selection

                                rank  revenues
company
Walmart                            1    485873
State Grid                         2    315199
Sinopec Group                      3    267518
China National Petroleum           4    262573
Toyota Motor                       5    254694
...                              ...       ...
Teva Pharmaceutical Industries   496     21903
New China Life Insurance         497     21796
Wm. Morrison Supermarkets        498     21741
TUI                              499     21655
AutoNation                       500     21609

[500 rows x 2 columns]

# Indexing a DataFrame using indexer attributes

Pandas provides some special indexer attributes that explicitly expose certain indexing schemes.

These are not functional methods, but attributes that expose a particular slicing interface to the data in the `Series`.

## The **`loc`** attribute

The **`loc`** attribute in Pandas is a property of a DataFrame used for label-based indexing and selection.

It allows accessing a group of rows and columns by using their labels (i.e., row and column names), rather than their integer positions.

This attribute allows indexing and slicing that always references the explicit index.

It selects data in a different way than just the indexing operator.

It can select subsets of rows or columns.

It can also simultaneously select subsets of rows and columns.

**Label-based:**

`loc` primarily operates on the labels of the index and columns. When slicing with `loc`, both the start and stop labels are inclusive, unlike standard Python slicing.

**Flexible input:**

It can accept various inputs for selecting rows and columns, including:
* A single label: `df.loc['row_label', 'col_label']`
* A list or array of labels: `df.loc[['row1', 'row2'], ['colA', 'colB']]`
* A slice object with labels: `df.loc['start_row':'end_row', 'start_col':'end_col']`
* A boolean array: `df.loc[df['column'] > 5]`

**Example:** select a single row with label Toyota Motor:

In [8]:
# select a single row
data_selection = data.loc['Toyota Motor']

# show dataframe
data_selection

rank                                     5
revenues                            254694
revenue_change                         7.7
profits                            16899.3
assets                              437575
profit_change                        -12.3
ceo                            Akio Toyoda
industry          Motor Vehicles and Parts
sector              Motor Vehicles & Parts
previous_rank                            8
country                              Japan
Name: Toyota Motor, dtype: object

**Example:** select rows with labels Toyota Motor and Volkswagen:

In [9]:
# select rows with labels Toyota Motor and Volkswagen
data_selection = data.loc[['Toyota Motor', 'Volkswagen']]

# show dataframe
data_selection

,rank,revenues,revenue_change,profits,assets,profit_change,ceo,industry,sector,previous_rank,country
company,,,,,,,,,,,
Toyota Motor,5,254694,7.7,16899.3,437575,-12.3,Akio Toyoda,Motor Vehicles and Parts,Motor Vehicles & Parts,8,Japan
Volkswagen,6,240264,1.5,5937.3,432116,NaN,Matthias Muller,Motor Vehicles and Parts,Motor Vehicles & Parts,7,Germany

**Example:** select rows with labels Toyota Motor and Volkswagen, and column with label revenues:

In [10]:
# select rows with labels Toyota Motor and Volkswagen, and column with label revenues
data_selection = data.loc[['Toyota Motor', 'Volkswagen'], 'revenues']

# show dataframe
data_selection

company
Toyota Motor    254694
Volkswagen      240264
Name: revenues, dtype: int64

**Example:** select row with label Toyota Motor, and columns with labels revenues and profits:

In [11]:
# select row with label Toyota Motor, and columns with labels revenues and profits
data_selection = data.loc['Toyota Motor', ['revenues', 'profits']]

# show dataframe
data_selection

revenues     254694
profits     16899.3
Name: Toyota Motor, dtype: object

**Example:** select rows with labels Toyota Motor and Volkswagen, and columns with labels revenues and profits:

In [12]:
# select rows with labels Toyota Motor and Volkswagen,
# and columns with labels revenues and profits
rows_labels = ['Toyota Motor', 'Volkswagen']
columns_labels = ['revenues', 'profits']
data_selection = data.loc[rows_labels, columns_labels]

# show dataframe
data_selection

              revenues  profits
company
Toyota Motor    254694  16899.3
Volkswagen      240264   5937.3

**Example:** select a slice of contiguous rows with labels ranging from Walmart to Toyota Motor, and a slice of contiguous columns with labels ranging from revenues to profit_change:

In [13]:
# select a slice of contiguous rows
# with labels ranging from Walmart to Toyota Motor
# and a slice of contiguous columns
# with labels ranging from revenues to profit_change
data_selection = data.loc['Walmart':'Toyota Motor', 'revenues':'profit_change']

# show dataframe
data_selection

,revenues,revenue_change,profits,assets,profit_change
company,,,,,
Walmart,485873,0.8,13643.0,198825,-7.2
State Grid,315199,-4.4,9571.3,489838,-6.2
Sinopec Group,267518,-9.1,1257.9,310726,-65.0
China National Petroleum,262573,-12.3,1867.5,585619,-73.7
Toyota Motor,254694,7.7,16899.3,437575,-12.3

# The **`iloc`** attribute

The **`iloc`** attribute allows indexing and slicing that always references the implicit Python-style index.

This attribute is used to select rows from a DataFrame.

In order to select a row using `iloc`, we need to specify the position of this row.

In [14]:
# select row by iloc method
data_selection = data.iloc[0]

# show dataframe
data_selection

rank                                  1
revenues                         485873
revenue_change                      0.8
profits                         13643.0
assets                           198825
profit_change                      -7.2
ceo                 C. Douglas McMillon
industry          General Merchandisers
sector                        Retailing
previous_rank                         1
country                             USA
Name: Walmart, dtype: object

**Example:** select rows with indices 0, 1 and 2, and columns with indices 1 and 2:

In [15]:
# select rows with indices 0, 1 and 2, and columns with indices 1 and 3
data_selection = data.iloc[[0, 1, 2], [1, 3]]

# show dataframe
data_selection

               revenues  profits
company
Walmart          485873  13643.0
State Grid       315199   9571.3
Sinopec Group    267518   1257.9